// Generated by tools/generate-item-sounds.mjs; preserves native row order.
// effectsound.json SHA256 b3b74338760f16197ef1f2b2e85604a875bd75ac92c8c84989ee5a225b5c3470
export function createItemSoundCatalog():Readonly<Record<string,readonly {readonly path:string;readonly volume:number}[]>>{return {
  "SWORD": [
    {
      "path": "/assets/audio/sfx/prim/snd/ui/itsword.wav",
      "volume": 80
    }
  ],
  "BLADE": [
    {
      "path": "/assets/audio/sfx/prim/snd/ui/itsword.wav",
      "volume": 80
    }
  ],
  "SPEAR": [
    {
      "path": "/assets/audio/sfx/prim/snd/ui/itpolearm.wav",
      "volume": 80
    }
  ],
  "BOW": [
    {
      "path": "/assets/audio/sfx/prim/snd/ui/itstaff.wav",
      "volume": 80
    }
  ],
  "QUIVER": [
    {
      "path": "/assets/audio/sfx/prim/snd/ui/itquiver.wav",
      "volume": 80
    }
  ],
  "TSWORD": [
    {
      "path": "/assets/audio/sfx/prim/snd/ui/itpolearm.wav",
      "volume": 80
    }
  ],
  "TBLADE": [
    {
      "path": "/assets/audio/sfx/prim/snd/ui/itpolearm.wav",
      "volume": 80
    }
  ],
  "DUELAXE": [
    {
      "path": "/assets/audio/sfx/prim/snd/ui/itaxe.wav",
      "volume": 80
    }
  ],
  "DAGGER": [
    {
      "path": "/assets/audio/sfx/prim/snd/ui/itchakram.wav",
      "volume": 80
    }
  ],
  "CROSSBOW": [
    {
      "path": "/assets/audio/sfx/prim/snd/ui/itstaff.wav",
      "volume": 80
    }
  ],
  "WAND": [
    {
      "path": "/assets/audio/sfx/prim/snd/ui/itbow.wav",
      "volume": 80
    }
  ],
  "STAFF": [
    {
      "path": "/assets/audio/sfx/prim/snd/ui/itstaff.wav",
      "volume": 80
    }
  ],
  "HARP": [
    {
      "path": "/assets/audio/sfx/prim/snd/ui/itstaff.wav",
      "volume": 80
    }
  ],
  "SHIELD": [
    {
      "path": "/assets/audio/sfx/prim/snd/ui/itshield.wav",
      "volume": 80
    }
  ],
  "HAMMER": [
    {
      "path": "/assets/audio/sfx/prim/snd/ui/ithammer.wav",
      "volume": 80
    }
  ],
  "HELM": [
    {
      "path": "/assets/audio/sfx/prim/snd/ui/ithelm.wav",
      "volume": 80
    }
  ],
  "BREASTPLATE": [
    {
      "path": "/assets/audio/sfx/prim/snd/ui/itbreastplate.wav",
      "volume": 80
    }
  ],
  "CUISSE": [
    {
      "path": "/assets/audio/sfx/prim/snd/ui/itcuisse.wav",
      "volume": 80
    }
  ],
  "PAULDRONS": [
    {
      "path": "/assets/audio/sfx/prim/snd/ui/itpauldron.wav",
      "volume": 80
    }
  ],
  "GAUNTLET": [
    {
      "path": "/assets/audio/sfx/prim/snd/ui/itgauntlet.wav",
      "volume": 80
    }
  ],
  "GREAVE": [
    {
      "path": "/assets/audio/sfx/prim/snd/ui/itgreave.wav",
      "volume": 80
    }
  ],
  "CAP": [
    {
      "path": "/assets/audio/sfx/prim/snd/ui/itcap.wav",
      "volume": 80
    }
  ],
  "ROBE": [
    {
      "path": "/assets/audio/sfx/prim/snd/ui/itrobe.wav",
      "volume": 80
    }
  ],
  "GLOVES": [
    {
      "path": "/assets/audio/sfx/prim/snd/ui/itglove.wav",
      "volume": 80
    }
  ],
  "SHOES": [
    {
      "path": "/assets/audio/sfx/prim/snd/ui/itshoes.wav",
      "volume": 80
    }
  ],
  "TRADER": [
    {
      "path": "/assets/audio/sfx/prim/snd/ui/itshoes.wav",
      "volume": 80
    }
  ],
  "THIEF": [
    {
      "path": "/assets/audio/sfx/prim/snd/ui/itrobe.wav",
      "volume": 80
    }
  ],
  "HUNTER": [
    {
      "path": "/assets/audio/sfx/prim/snd/ui/itgauntlet.wav",
      "volume": 80
    }
  ],
  "RING": [
    {
      "path": "/assets/audio/sfx/prim/snd/ui/itring.wav",
      "volume": 80
    }
  ],
  "NECKLACE": [
    {
      "path": "/assets/audio/sfx/prim/snd/ui/itring.wav",
      "volume": 80
    }
  ],
  "EARRING": [
    {
      "path": "/assets/audio/sfx/prim/snd/ui/itring.wav",
      "volume": 80
    }
  ],
  "MOBPIECE": [
    {
      "path": "/assets/audio/sfx/prim/snd/ui/itmonsterpiece.wav",
      "volume": 80
    }
  ],
  "TABLET": [
    {
      "path": "/assets/audio/sfx/prim/snd/ui/ittablet.wav",
      "volume": 80
    }
  ],
  "SCROLL": [
    {
      "path": "/assets/audio/sfx/prim/snd/ui/itscroll.wav",
      "volume": 80
    }
  ],
  "HERB": [
    {
      "path": "/assets/audio/sfx/prim/snd/ui/ithub.wav",
      "volume": 80
    }
  ],
  "POTION": [
    {
      "path": "/assets/audio/sfx/prim/snd/ui/itpotion.wav",
      "volume": 80
    }
  ],
  "METAL": [
    {
      "path": "/assets/audio/sfx/prim/snd/ui/itmetal.wav",
      "volume": 80
    }
  ]
};}
export function createItemDropSoundCatalog():Readonly<Record<string,readonly {readonly path:string;readonly volume:number}[]>>{return {
  "GOLD": [
    {
      "path": "/assets/audio/sfx/prim/snd/ui/itgold.wav",
      "volume": 80
    }
  ]
};}
