/*
===========================================================================

generated.go - composition of curated and generated quest definitions

The embedded projection contains data, not executable scripts. Every row
passes the same version-aware loader and reference validation as curated
native handlers. Research directories are never runtime dependencies.

===========================================================================
*/
package quest

import (
	"bytes"
	_ "embed"
	"encoding/json"
	"fmt"
)

//go:embed catalog_generated.json
var generatedCatalog []byte

// Generated by research/tools/scripts/analysis/project_quest_achieved_now.py
// from the recovered v1.150 quest scripts: codename -> ACHIEVED_NOW symbol.
//
//go:embed achieved_now_generated.json
var achievedNowCatalog []byte

// Generated by scripts/build/generate_compiled_quests.py from the v1.188
// compiled quest classes, the v1.150 quest text and the SQL reward rows:
// the quests whose v1.150 script did not survive.
//
//go:embed .generated/compiled_quests.json
var compiledCatalog []byte

/*
================
catalogSpecs

Small protocol fixtures contain only their authored subset. Production's
complete media catalog admits every corresponding compiled contract.
================
*/
func catalogSpecs(catalog *Catalog) ([]QuestSpec, error) {
	specs := append([]QuestSpec(nil), curatedQuestSpecs...)
	generated, err := decodeSpecs("generated quest catalog", generatedCatalog)
	if err != nil {
		return nil, err
	}
	compiled, err := decodeSpecs("compiled quest catalog", compiledCatalog)
	if err != nil {
		return nil, err
	}
	additional := append([]QuestSpec(nil), europeanTutorialSpecs...)
	additional = append(additional, captureQuestSpecs...)
	additional = append(additional, generated...)
	authored := map[string]bool{}
	for _, spec := range append(specs, additional...) {
		authored[spec.Codename] = true
	}
	// A compiled class stands only for a quest nothing else authors: a
	// curated spec already ports its custom behaviour.
	for _, spec := range compiled {
		if !authored[spec.Codename] {
			additional = append(additional, spec)
		}
	}
	for _, spec := range additional {
		// The small protocol-test catalogs intentionally contain only their own
		// rows. Production loads the complete verified v1.150 media catalog.
		if _, ok := catalog.QuestByCodename(spec.Codename); ok {
			specs = append(specs, spec)
		}
	}
	if err := applyAchievedNow(specs); err != nil {
		return nil, err
	}
	return specs, nil
}

/*
================
decodeSpecs

One embedded spec table; an unknown field is a generator defect.
================
*/
func decodeSpecs(name string, raw []byte) ([]QuestSpec, error) {
	var specs []QuestSpec
	decoder := json.NewDecoder(bytes.NewReader(raw))
	decoder.DisallowUnknownFields()
	if err := decoder.Decode(&specs); err != nil {
		return nil, fmt.Errorf("%s: %w", name, err)
	}
	return specs, nil
}

/*
================
applyAchievedNow

The recovered script's ACHIEVED_NOW symbol fills every spec it names. A
curated spec keeps its own symbol only where no script survived; one that
disagrees with its script is an authoring error.
================
*/
func applyAchievedNow(specs []QuestSpec) error {
	var symbols map[string]string
	if err := json.Unmarshal(achievedNowCatalog, &symbols); err != nil {
		return fmt.Errorf("achieved-now catalog: %w", err)
	}
	for i := range specs {
		symbol, ok := symbols[specs[i].Codename]
		if !ok {
			continue
		}
		if specs[i].AchievedNowSymbol != "" && specs[i].AchievedNowSymbol != symbol {
			return fmt.Errorf("quest %s achieved-now %s contradicts its script's %s", specs[i].Codename, specs[i].AchievedNowSymbol, symbol)
		}
		specs[i].AchievedNowSymbol = symbol
	}
	return nil
}
