export default {
  name: "assets",
  description: "Asset build, packing, cache, and authored-resource contracts",
  runner: "node",
  files: [
    "scripts/test/assets/bsrParticleModifiers.test.mjs",
    "scripts/test/assets/assetDeliveryOwnership.test.mjs",
    "scripts/test/assets/nativeUiTexture.test.mjs",
    "scripts/test/assets/fontAtlasPublication.test.mjs",
    "scripts/test/assets/buildSharedUtilities.test.mjs",
    "scripts/test/assets/jsonAssetCompression.test.mjs",
    "scripts/test/assets/vatPipeline.test.mjs",
    "scripts/test/assets/resourceBuildGraph.test.mjs",
    "scripts/test/assets/publishedAssetBoundary.test.mjs",
    "scripts/test/assets/generatedAssetMembership.test.mjs",
    "scripts/test/assets/npcModelPublication.test.mjs",
    "scripts/test/assets/cifSpriteCatalog.test.mjs",
    "scripts/test/assets/skillPaneImageReferences.test.mjs",
    "scripts/test/world/worldMapImageReferences.test.mjs",
    "scripts/test/mission/effectProgramClosure.test.mjs",
    "scripts/test/assets/characterModelAssetContracts.test.mjs",
    "scripts/test/assets/actorLocomotionRootMotion.test.mjs",
    "scripts/test/assets/banTimeline.test.mjs",
    "scripts/test/assets/npcAnimationContactMarkers.test.mjs",
    "scripts/test/mission/missionMinimapBuild.test.mjs",
    "scripts/test/mission/minimapArtCoverage.test.mjs",
    "scripts/test/world/authoredWorldRegionResources.test.mjs",
    "scripts/test/assets/assetPackIntegrity.test.mjs",
    "scripts/test/assets/rebuildLockInterop.test.mjs",
    "scripts/test/assets/assetPackGroupParity.test.mjs",
    "scripts/test/assets/assetPackOwnership.test.mjs",
    "scripts/test/assets/pythonRun.test.mjs",
    "scripts/test/assets/optionalDataAsset.test.mjs",
    "scripts/test/assets/nameFilterAsset.test.mjs"
  ]
};
