package gamedata

import (
	"fmt"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"sync"

	"opensro.online/server/internal/config"
)

const (
	// EnvRoot names the immutable server projection generated by the monorepo
	// resource build. Runtime code never reads browser-public or extraction
	// directories.
	EnvRoot = "SRO_SERVER_GAME_DATA_ROOT"
	// EnvManifestDigest optionally pins the exact deployment manifest. Local
	// development may leave it empty; production should not.
	EnvManifestDigest = "SRO_SERVER_GAME_DATA_MANIFEST_DIGEST"
)

// defaultRoot is module-relative: the projection lives inside the module, so
// its tests read only module files and `go test` validates cached results
// against it (apps/server/AGENTS.md).
var defaultRoot = filepath.Join(".generated", "game-data", SupportedGameVersion, SupportedProjection)

type resolveResult struct {
	ready chan struct{}
	paths Paths
	err   error
}

var (
	resolveMu    sync.Mutex
	resolveCache = make(map[string]*resolveResult)
)

// Paths is the verified process-level game-data identity shared by every
// authority and gameplay loader.
type Paths struct {
	RuntimeRoot           string
	BundleRoot            string
	ManifestDigest        string
	CharacterAuthorityDir string
	TextdataDir           string
	WorldAuthorityDir     string
}

// Resolve opens and cryptographically verifies the server projection.
func Resolve() (Paths, error) {
	root := strings.TrimSpace(os.Getenv(EnvRoot))
	if root == "" {
		moduleRoot, err := mainModuleRoot()
		if err != nil {
			return Paths{}, fmt.Errorf("%s is required outside the source checkout: %w", EnvRoot, err)
		}
		root = filepath.Join(moduleRoot, defaultRoot)
		if _, err := os.Stat(root); err != nil {
			root += ".srogz"
		}
	}
	runtimeRoot, err := filepath.Abs(root)
	if err != nil {
		return Paths{}, fmt.Errorf("resolve server game-data artifact: %w", err)
	}
	expectedManifestDigest := strings.TrimSpace(os.Getenv(EnvManifestDigest))
	cacheKey, err := resolveIdentity(runtimeRoot, expectedManifestDigest)
	if err != nil {
		return Paths{}, fmt.Errorf("identify server game-data artifact: %w", err)
	}
	return resolveCached(cacheKey, runtimeRoot, expectedManifestDigest)
}

/*
==================
mainModuleRoot

The server module of the main checkout: a linked git worktree reads the
projection the main checkout built (config.MainCheckoutRoot), as the
scripts and the tests do. Outside a git checkout it is the module itself.
==================
*/
func mainModuleRoot() (string, error) {
	moduleRoot, err := config.FindModuleRoot()
	if err != nil {
		return "", err
	}
	checkout := filepath.Join(moduleRoot, "..", "..")
	main, err := config.MainCheckoutRoot(checkout)
	if err != nil {
		return "", err
	}
	if err := config.RequireNoWorktreeCopies(checkout, main); err != nil {
		return "", err
	}
	inCheckout, err := filepath.Rel(filepath.Clean(checkout), moduleRoot)
	if err != nil {
		return "", err
	}
	return filepath.Join(main, inCheckout), nil
}

// resolveCached verifies one immutable deployment artifact exactly once per
// process. Concurrent callers share the same first-open work; only successful
// verifications are retained. The key includes the artifact and manifest file
// identities plus every deployment pin/path knob, so replacing an artifact or
// changing configuration forces a fresh cryptographic verification.
func resolveCached(cacheKey, runtimeRoot, expectedManifestDigest string) (Paths, error) {
	resolveMu.Lock()
	if cached := resolveCache[cacheKey]; cached != nil {
		resolveMu.Unlock()
		<-cached.ready
		return cached.paths, cached.err
	}
	result := &resolveResult{ready: make(chan struct{})}
	resolveCache[cacheKey] = result
	resolveMu.Unlock()

	paths, resolveErr := resolveUncached(runtimeRoot, expectedManifestDigest)
	resolveMu.Lock()
	result.paths = paths
	result.err = resolveErr
	if resolveErr != nil {
		delete(resolveCache, cacheKey)
	}
	close(result.ready)
	resolveMu.Unlock()
	return paths, resolveErr
}

func resolveUncached(runtimeRoot, expectedManifestDigest string) (Paths, error) {
	root, err := materializeArchive(runtimeRoot)
	if err != nil {
		return Paths{}, fmt.Errorf("materialize server game-data projection: %w", err)
	}
	bundle, err := Open(root, expectedManifestDigest)
	if err != nil {
		return Paths{}, fmt.Errorf("open server game-data projection: %w", err)
	}
	return Paths{
		RuntimeRoot:           filepath.Clean(runtimeRoot),
		BundleRoot:            bundle.Root,
		ManifestDigest:        bundle.ManifestDigest,
		CharacterAuthorityDir: bundle.CharacterAuthorityDir,
		TextdataDir:           bundle.TextdataDir,
		WorldAuthorityDir:     bundle.WorldAuthorityDir,
	}, nil
}

func resolveIdentity(runtimeRoot, expectedManifestDigest string) (string, error) {
	realRoot, err := filepath.EvalSymlinks(runtimeRoot)
	if err != nil {
		return "", err
	}
	info, err := os.Stat(realRoot)
	if err != nil {
		return "", err
	}
	parts := []string{
		filepath.Clean(realRoot),
		strconv.FormatBool(info.IsDir()),
		strconv.FormatInt(info.Size(), 10),
		strconv.FormatInt(info.ModTime().UnixNano(), 10),
		expectedManifestDigest,
		strings.TrimSpace(os.Getenv(EnvCacheRoot)),
	}
	if info.IsDir() {
		manifestInfo, statErr := os.Stat(filepath.Join(realRoot, ManifestFilename))
		if statErr != nil {
			return "", statErr
		}
		parts = append(
			parts,
			strconv.FormatInt(manifestInfo.Size(), 10),
			strconv.FormatInt(manifestInfo.ModTime().UnixNano(), 10),
		)
	}
	return strings.Join(parts, "\x00"), nil
}

// ResolveTextdataDir is the narrow accessor used by offline evidence and
// migration tools. It still resolves through the verified projection.
func ResolveTextdataDir() (string, error) {
	paths, err := Resolve()
	if err != nil {
		return "", err
	}
	return paths.TextdataDir, nil
}
